### ISSUE TITLE
[Feature Request] How to add custom icons as seats

### ISSUE THREAD

**Issue by kirantpatil** [mateuszmarkowski/jQuery-Seat-Charts#45]
Hi,

I would like to add custom icon as seat.

Is it possible now ?

If yes then how to do it ?

Thanks.

**Comment by mateuszmarkowski** [comment]
Please see the [Styling](https://github.com/mateuszmarkowski/jQuery-Seat-Charts#styling) section. The default CSS classes are very basic and use background-color but it doesn't mean that you can't use more sophisticated background features such as for example:

```css
div.seatCharts-seat.selected {
   background: url(http://your-backgrund-url.com/image.png);
   background-size: contain;
}
```
